# Generated by Django 3.1.7 on 2021-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210809_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
    ]
