# Generated by Django 3.1.7 on 2021-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='asset_tickers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
